### ISSUE TITLE
uninitialized constant Bio::Shell::Ghost::Readline (NameError) when launching the shell under Ruby 3

### ISSUE THREAD

**Issue by hkokubun2017** [bioruby/bioruby-shell#2]
An error "core.rb:400:in `block in load_history_file': uninitialized constant Bio::Shell::Ghost::Readline (NameError)" occurs when the bioruby shell is started and the history file exists in Ruby version 3 and up.

This is caused because Ruby 3 does not include Readline module as builtin library. Adding "require 'readline' if RUBY_VERSION >= '3'" solved the error caused in load_history_file that calls Readline.

This quick fix seemed worked, however, on further testing, I realized that the loaded command history is that of Ruby’s plain irb although the error went away. Further investigation is needed.

I created a simple pull request, so please guide me through because this is my very first issue and PR.

**Comment by ngoto** [comment]
fix for the bug is included in bio-shell-1.0.1.gem
